// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pkg/model/visa/grpc/v1/visa.proto

package visa

import (
	error1 "github.com/mhthrh/common_pkg/pkg/xErrors/grpc/error"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	PayoutMethod                string                 `protobuf:"bytes,1,opt,name=PayoutMethod,proto3" json:"PayoutMethod,omitempty"`
	RecipientDetail             *Recipient             `protobuf:"bytes,2,opt,name=RecipientDetail,proto3" json:"RecipientDetail,omitempty"`
	InitiatingPartyId           string                 `protobuf:"bytes,3,opt,name=InitiatingPartyId,proto3" json:"InitiatingPartyId,omitempty"`
	ClientVerificationReference string                 `protobuf:"bytes,4,opt,name=ClientVerificationReference,proto3" json:"ClientVerificationReference,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_model_visa_grpc_v1_visa_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyRequest) GetPayoutMethod() string {
	if x != nil {
		return x.PayoutMethod
	}
	return ""
}

func (x *VerifyRequest) GetRecipientDetail() *Recipient {
	if x != nil {
		return x.RecipientDetail
	}
	return nil
}

func (x *VerifyRequest) GetInitiatingPartyId() string {
	if x != nil {
		return x.InitiatingPartyId
	}
	return ""
}

func (x *VerifyRequest) GetClientVerificationReference() string {
	if x != nil {
		return x.ClientVerificationReference
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Reference     string                 `protobuf:"bytes,3,opt,name=Reference,proto3" json:"Reference,omitempty"`
	AcVerify      *AccountVerification   `protobuf:"bytes,4,opt,name=AcVerify,proto3" json:"AcVerify,omitempty"`
	Error         *error1.Error          `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_model_visa_grpc_v1_visa_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyResponse) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *VerifyResponse) GetAcVerify() *AccountVerification {
	if x != nil {
		return x.AcVerify
	}
	return nil
}

func (x *VerifyResponse) GetError() *error1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type AccountVerification struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AccountIdentifierMatch string                 `protobuf:"bytes,1,opt,name=AccountIdentifierMatch,proto3" json:"AccountIdentifierMatch,omitempty"`
	NameMatch              string                 `protobuf:"bytes,2,opt,name=NameMatch,proto3" json:"NameMatch,omitempty"`
	BankAccountName        string                 `protobuf:"bytes,3,opt,name=BankAccountName,proto3" json:"BankAccountName,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AccountVerification) Reset() {
	*x = AccountVerification{}
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountVerification) ProtoMessage() {}

func (x *AccountVerification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountVerification.ProtoReflect.Descriptor instead.
func (*AccountVerification) Descriptor() ([]byte, []int) {
	return file_pkg_model_visa_grpc_v1_visa_proto_rawDescGZIP(), []int{2}
}

func (x *AccountVerification) GetAccountIdentifierMatch() string {
	if x != nil {
		return x.AccountIdentifierMatch
	}
	return ""
}

func (x *AccountVerification) GetNameMatch() string {
	if x != nil {
		return x.NameMatch
	}
	return ""
}

func (x *AccountVerification) GetBankAccountName() string {
	if x != nil {
		return x.BankAccountName
	}
	return ""
}

type BankR struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BankName          string                 `protobuf:"bytes,1,opt,name=BankName,proto3" json:"BankName,omitempty"`
	AccountName       string                 `protobuf:"bytes,2,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,3,opt,name=AccountNumber,proto3" json:"AccountNumber,omitempty"`
	AccountNumberType string                 `protobuf:"bytes,4,opt,name=AccountNumberType,proto3" json:"AccountNumberType,omitempty"`
	CountryCode       string                 `protobuf:"bytes,5,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
	BankCode          string                 `protobuf:"bytes,6,opt,name=BankCode,proto3" json:"BankCode,omitempty"`
	BankCodeType      string                 `protobuf:"bytes,7,opt,name=BankCodeType,proto3" json:"BankCodeType,omitempty"`
	CurrencyCode      string                 `protobuf:"bytes,8,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BankR) Reset() {
	*x = BankR{}
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankR) ProtoMessage() {}

func (x *BankR) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankR.ProtoReflect.Descriptor instead.
func (*BankR) Descriptor() ([]byte, []int) {
	return file_pkg_model_visa_grpc_v1_visa_proto_rawDescGZIP(), []int{3}
}

func (x *BankR) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *BankR) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BankR) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BankR) GetAccountNumberType() string {
	if x != nil {
		return x.AccountNumberType
	}
	return ""
}

func (x *BankR) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *BankR) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *BankR) GetBankCodeType() string {
	if x != nil {
		return x.BankCodeType
	}
	return ""
}

func (x *BankR) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type Recipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bank          *BankR                 `protobuf:"bytes,1,opt,name=Bank,proto3" json:"Bank,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_visa_grpc_v1_visa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_pkg_model_visa_grpc_v1_visa_proto_rawDescGZIP(), []int{4}
}

func (x *Recipient) GetBank() *BankR {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *Recipient) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Recipient) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Recipient) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

var File_pkg_model_visa_grpc_v1_visa_proto protoreflect.FileDescriptor

const file_pkg_model_visa_grpc_v1_visa_proto_rawDesc = "" +
	"\n" +
	"!pkg/model/visa/grpc/v1/visa.proto\x12\x04visa\x1a#pkg/xErrors/grpc/error/gError.proto\"\xde\x01\n" +
	"\rVerifyRequest\x12\"\n" +
	"\fPayoutMethod\x18\x01 \x01(\tR\fPayoutMethod\x129\n" +
	"\x0fRecipientDetail\x18\x02 \x01(\v2\x0f.visa.RecipientR\x0fRecipientDetail\x12,\n" +
	"\x11InitiatingPartyId\x18\x03 \x01(\tR\x11InitiatingPartyId\x12@\n" +
	"\x1bClientVerificationReference\x18\x04 \x01(\tR\x1bClientVerificationReference\"\xad\x01\n" +
	"\x0eVerifyResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\x12\x1c\n" +
	"\tReference\x18\x03 \x01(\tR\tReference\x125\n" +
	"\bAcVerify\x18\x04 \x01(\v2\x19.visa.AccountVerificationR\bAcVerify\x12\"\n" +
	"\x05Error\x18\x05 \x01(\v2\f.error.ErrorR\x05Error\"\x95\x01\n" +
	"\x13AccountVerification\x126\n" +
	"\x16AccountIdentifierMatch\x18\x01 \x01(\tR\x16AccountIdentifierMatch\x12\x1c\n" +
	"\tNameMatch\x18\x02 \x01(\tR\tNameMatch\x12(\n" +
	"\x0fBankAccountName\x18\x03 \x01(\tR\x0fBankAccountName\"\x9f\x02\n" +
	"\x05BankR\x12\x1a\n" +
	"\bBankName\x18\x01 \x01(\tR\bBankName\x12 \n" +
	"\vAccountName\x18\x02 \x01(\tR\vAccountName\x12$\n" +
	"\rAccountNumber\x18\x03 \x01(\tR\rAccountNumber\x12,\n" +
	"\x11AccountNumberType\x18\x04 \x01(\tR\x11AccountNumberType\x12 \n" +
	"\vCountryCode\x18\x05 \x01(\tR\vCountryCode\x12\x1a\n" +
	"\bBankCode\x18\x06 \x01(\tR\bBankCode\x12\"\n" +
	"\fBankCodeType\x18\a \x01(\tR\fBankCodeType\x12\"\n" +
	"\fCurrencyCode\x18\b \x01(\tR\fCurrencyCode\"z\n" +
	"\tRecipient\x12\x1f\n" +
	"\x04Bank\x18\x01 \x01(\v2\v.visa.BankRR\x04Bank\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x1a\n" +
	"\bLastName\x18\x03 \x01(\tR\bLastName\x12\x1c\n" +
	"\tFirstName\x18\x04 \x01(\tR\tFirstName2D\n" +
	"\vVisaService\x125\n" +
	"\x06Verify\x12\x13.visa.VerifyRequest\x1a\x14.visa.VerifyResponse\"\x00B:Z8github.com/mhthrh/common_pkg/pkg/model/visa/grpc/v1/visab\x06proto3"

var (
	file_pkg_model_visa_grpc_v1_visa_proto_rawDescOnce sync.Once
	file_pkg_model_visa_grpc_v1_visa_proto_rawDescData []byte
)

func file_pkg_model_visa_grpc_v1_visa_proto_rawDescGZIP() []byte {
	file_pkg_model_visa_grpc_v1_visa_proto_rawDescOnce.Do(func() {
		file_pkg_model_visa_grpc_v1_visa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_model_visa_grpc_v1_visa_proto_rawDesc), len(file_pkg_model_visa_grpc_v1_visa_proto_rawDesc)))
	})
	return file_pkg_model_visa_grpc_v1_visa_proto_rawDescData
}

var file_pkg_model_visa_grpc_v1_visa_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_model_visa_grpc_v1_visa_proto_goTypes = []any{
	(*VerifyRequest)(nil),       // 0: visa.VerifyRequest
	(*VerifyResponse)(nil),      // 1: visa.VerifyResponse
	(*AccountVerification)(nil), // 2: visa.AccountVerification
	(*BankR)(nil),               // 3: visa.BankR
	(*Recipient)(nil),           // 4: visa.Recipient
	(*error1.Error)(nil),        // 5: error.Error
}
var file_pkg_model_visa_grpc_v1_visa_proto_depIdxs = []int32{
	4, // 0: visa.VerifyRequest.RecipientDetail:type_name -> visa.Recipient
	2, // 1: visa.VerifyResponse.AcVerify:type_name -> visa.AccountVerification
	5, // 2: visa.VerifyResponse.Error:type_name -> error.Error
	3, // 3: visa.Recipient.Bank:type_name -> visa.BankR
	0, // 4: visa.VisaService.Verify:input_type -> visa.VerifyRequest
	1, // 5: visa.VisaService.Verify:output_type -> visa.VerifyResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_model_visa_grpc_v1_visa_proto_init() }
func file_pkg_model_visa_grpc_v1_visa_proto_init() {
	if File_pkg_model_visa_grpc_v1_visa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_model_visa_grpc_v1_visa_proto_rawDesc), len(file_pkg_model_visa_grpc_v1_visa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_model_visa_grpc_v1_visa_proto_goTypes,
		DependencyIndexes: file_pkg_model_visa_grpc_v1_visa_proto_depIdxs,
		MessageInfos:      file_pkg_model_visa_grpc_v1_visa_proto_msgTypes,
	}.Build()
	File_pkg_model_visa_grpc_v1_visa_proto = out.File
	file_pkg_model_visa_grpc_v1_visa_proto_goTypes = nil
	file_pkg_model_visa_grpc_v1_visa_proto_depIdxs = nil
}
