// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pkg/model/user/grpc/v1/user.proto

package user

import (
	error1 "github.com/mhthrh/common_pkg/pkg/xErrors/grpc/error"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_pkg_model_user_grpc_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_user_grpc_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_model_user_grpc_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserName) Reset() {
	*x = UserName{}
	mi := &file_pkg_model_user_grpc_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserName) ProtoMessage() {}

func (x *UserName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_user_grpc_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserName.ProtoReflect.Descriptor instead.
func (*UserName) Descriptor() ([]byte, []int) {
	return file_pkg_model_user_grpc_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserName) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usr           *UserRequest           `protobuf:"bytes,1,opt,name=usr,proto3" json:"usr,omitempty"`
	Error         *error1.Error          `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_pkg_model_user_grpc_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_user_grpc_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_model_user_grpc_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetUsr() *UserRequest {
	if x != nil {
		return x.Usr
	}
	return nil
}

func (x *UserResponse) GetError() *error1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_pkg_model_user_grpc_v1_user_proto protoreflect.FileDescriptor

const file_pkg_model_user_grpc_v1_user_proto_rawDesc = "" +
	"\n" +
	"!pkg/model/user/grpc/v1/user.proto\x12\x04user\x1a#pkg/xErrors/grpc/error/gError.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb7\x01\n" +
	"\vUserRequest\x12\x1c\n" +
	"\tFirstName\x18\x01 \x01(\tR\tFirstName\x12\x1a\n" +
	"\bLastName\x18\x02 \x01(\tR\bLastName\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12 \n" +
	"\vPhoneNumber\x18\x04 \x01(\tR\vPhoneNumber\x12\x1a\n" +
	"\bUserName\x18\x05 \x01(\tR\bUserName\x12\x1a\n" +
	"\bPassword\x18\x06 \x01(\tR\bPassword\"&\n" +
	"\bUserName\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"W\n" +
	"\fUserResponse\x12#\n" +
	"\x03usr\x18\x01 \x01(\v2\x11.user.UserRequestR\x03usr\x12\"\n" +
	"\x05Error\x18\x02 \x01(\v2\f.error.ErrorR\x05Error2\xe6\x01\n" +
	"\vUserService\x125\n" +
	"\x06Create\x12\x11.user.UserRequest\x1a\x16.google.protobuf.Empty\"\x00\x125\n" +
	"\rGetByUserName\x12\x0e.user.UserName\x1a\x12.user.UserResponse\"\x00\x125\n" +
	"\x06Update\x12\x11.user.UserRequest\x1a\x16.google.protobuf.Empty\"\x00\x122\n" +
	"\x06Remove\x12\x0e.user.UserName\x1a\x16.google.protobuf.Empty\"\x00B:Z8github.com/mhthrh/common_pkg/pkg/model/user/grpc/v1/userb\x06proto3"

var (
	file_pkg_model_user_grpc_v1_user_proto_rawDescOnce sync.Once
	file_pkg_model_user_grpc_v1_user_proto_rawDescData []byte
)

func file_pkg_model_user_grpc_v1_user_proto_rawDescGZIP() []byte {
	file_pkg_model_user_grpc_v1_user_proto_rawDescOnce.Do(func() {
		file_pkg_model_user_grpc_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_model_user_grpc_v1_user_proto_rawDesc), len(file_pkg_model_user_grpc_v1_user_proto_rawDesc)))
	})
	return file_pkg_model_user_grpc_v1_user_proto_rawDescData
}

var file_pkg_model_user_grpc_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_model_user_grpc_v1_user_proto_goTypes = []any{
	(*UserRequest)(nil),   // 0: user.UserRequest
	(*UserName)(nil),      // 1: user.UserName
	(*UserResponse)(nil),  // 2: user.UserResponse
	(*error1.Error)(nil),  // 3: error.Error
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_pkg_model_user_grpc_v1_user_proto_depIdxs = []int32{
	0, // 0: user.UserResponse.usr:type_name -> user.UserRequest
	3, // 1: user.UserResponse.Error:type_name -> error.Error
	0, // 2: user.UserService.Create:input_type -> user.UserRequest
	1, // 3: user.UserService.GetByUserName:input_type -> user.UserName
	0, // 4: user.UserService.Update:input_type -> user.UserRequest
	1, // 5: user.UserService.Remove:input_type -> user.UserName
	4, // 6: user.UserService.Create:output_type -> google.protobuf.Empty
	2, // 7: user.UserService.GetByUserName:output_type -> user.UserResponse
	4, // 8: user.UserService.Update:output_type -> google.protobuf.Empty
	4, // 9: user.UserService.Remove:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_model_user_grpc_v1_user_proto_init() }
func file_pkg_model_user_grpc_v1_user_proto_init() {
	if File_pkg_model_user_grpc_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_model_user_grpc_v1_user_proto_rawDesc), len(file_pkg_model_user_grpc_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_model_user_grpc_v1_user_proto_goTypes,
		DependencyIndexes: file_pkg_model_user_grpc_v1_user_proto_depIdxs,
		MessageInfos:      file_pkg_model_user_grpc_v1_user_proto_msgTypes,
	}.Build()
	File_pkg_model_user_grpc_v1_user_proto = out.File
	file_pkg_model_user_grpc_v1_user_proto_goTypes = nil
	file_pkg_model_user_grpc_v1_user_proto_depIdxs = nil
}
