name: check code and run tests

on:
  push:
    branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go

    steps:
      - uses: actions/checkout@v4

      - name: go setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'


#      - name: Install vet tool
#        run: |
#          go install golang.org/x/tools/cmd/vet@latest
#          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: List files
        run: ls -R

      - name: Show current path
        run: pwd
      - name: Use GOPATH
        run: echo  $GOPATH

      - name: move project
        run: |
          mkdir -p "$GOPATH/src/common_pkg/config/file"
          cp ./config/file/* "$GOPATH/src/common_pkg/config/file"

      - name: check code
        run: go vet ./...

      - name: Test
        run: go test ./pkg/... ./util/... -v -bench . -failfast -cover -count=1
