name: check code and run tests

on:
  push:
    branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.4'

      - name: check code
        run: go vet ./...

      - name: Test
        run: go test ./... -v -bench . -failfast -cover -count=1
