name: check code and run tests

on:
  push:
    branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

#      - name: Install vet tool
#        run: |
#          go install golang.org/x/tools/cmd/vet@latest
#          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: check code
        run: go vet ./...

      - name: Test
        run: go test ./... -v -bench . -failfast -cover -count=1
